diff --git a/kernel/linux-imx-rel_imx_4.1.15_2.1.0_ga/mm/Makefile b/kernel/linux-imx-rel_imx_4.1.15_2.1.0_ga/mm/Makefile
index 98c4eae..e22f879 100644
--- a/kernel/linux-imx-rel_imx_4.1.15_2.1.0_ga/mm/Makefile
+++ b/kernel/linux-imx-rel_imx_4.1.15_2.1.0_ga/mm/Makefile
@@ -20,7 +20,7 @@ obj-y			:= filemap.o mempool.o oom_kill.o \
 			   util.o mmzone.o vmstat.o backing-dev.o \
 			   mm_init.o mmu_context.o percpu.o slab_common.o \
 			   compaction.o vmacache.o \
-			   interval_tree.o list_lru.o workingset.o \
+			   interval_tree.o list_lru.o workingset.o slubdebug.o\
 			   debug.o $(mmu-y)
 
 obj-y += init-mm.o
